HEADER_USERNAME = 'USERNAME'
HEADER_CONTEXTID = 'CONTEXTID'
HEADER_EVENTTYPE = 'EVENTTYPE'
HEADER_TIMESTAMP = 'TIMESTAMP'
HEADER_REMOTEIP = 'REMOTEIP'
HEADER_AUTHENTICATIONSUCCESS = 'AUTHENTICATIONSUCCESS'

EVENTYPE_STEP = 'step'
EVENTYPE_OVERALL = 'overall'