from enum import Enum

HEADER_USERNAME = 'USERNAME'
HEADER_CONTEXTID = 'CONTEXTID'
HEADER_EVENTTYPE = 'EVENTTYPE'
HEADER_TIMESTAMP = 'TIMESTAMP'
HEADER_REMOTEIP = 'REMOTEIP'
HEADER_AUTHENTICATIONSUCCESS = 'AUTHENTICATIONSUCCESS'
HEADER_LATITUDE = 'LATITUDE'
HEADER_LONGITUDE = 'LONGITITUDE'
HEADER_COUNTRY = 'COUNTRY'
HEADER_SUSPICIOUS_LOGIN = 'SUSPICIOUS_LOGIN'

EVENTYPE_STEP = 'step'
EVENTYPE_OVERALL = 'overall'